version: '3.1'

services:

  db:
    image: postgres
    restart: always
    volumes:
      - ./postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - 8025:8025
    expose:
      - 1025